### ISSUE TITLE
560和560D

### ISSUE THREAD

**Issue by zaifoo** [heyxiaobai/Asrock-Z370m-Pro4-Hackintosh#1]
你好。那些三线品牌的全新560或560D好驱动吗？精影这个牌子的560了解不？

**Comment by heyxiaobai** [comment]
你好，据我了解，560个别型号HDMI/DVI输出黑屏，需要改FB，DP正常输出；560D是全部正常。精影这个不太了解，黑果显卡还是推荐蓝宝石 微星的。
